/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdad4",
        "surface-tint": "#9a442d",
        "text-main": "#3D405B",
        "surface-container-highest": "#dfe0ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "background": "#fbf8ff",
        "border-subtle": "#E2E8F0",
        "on-secondary-container": "#795c57",
        "surface-variant": "#dfe0ff",
        "secondary-fixed-dim": "#e3beb8",
        "secondary-container": "#fed7d0",
        "surface-container-high": "#e6e6ff",
        "on-background": "#161a32",
        "secondary": "#745853",
        "tertiary": "#006b5b",
        "on-surface": "#161a32",
        "tertiary-fixed-dim": "#5edbc1",
        "on-tertiary-container": "#00362d",
        "outline": "#88726d",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbd2",
        "on-primary": "#ffffff",
        "text-secondary": "#6B7280",
        "on-secondary": "#ffffff",
        "surface-card": "#FFFFFF",
        "primary-fixed-dim": "#ffb4a1",
        "surface-dim": "#d6d8f9",
        "inverse-on-surface": "#f1efff",
        "surface-muted": "#F4F3F0",
        "outline-variant": "#dbc1ba",
        "surface-container-low": "#f4f2ff",
        "on-surface-variant": "#55423e",
        "status-error": "#E63946",
        "on-primary-fixed-variant": "#7c2e19",
        "on-primary-container": "#5b1604",
        "surface-bright": "#fbf8ff",
        "error": "#ba1a1a",
        "primary-container": "#e07a5f",
        "app-bg": "#FAF9F6",
        "surface": "#fbf8ff",
        "primary": "#9a442d",
        "on-secondary-fixed": "#2b1613",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#00201a",
        "surface-container": "#edecff",
        "status-success": "#81B29A",
        "inverse-surface": "#2b2e48",
        "on-secondary-fixed-variant": "#5b403c",
        "tertiary-fixed": "#7df7dd",
        "inverse-primary": "#ffb4a1",
        "tertiary-container": "#19a992",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3c0800",
        "on-tertiary-fixed-variant": "#005144",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "xl": "32px",
        "md": "16px",
        "xs": "8px",
        "lg": "24px",
        "sm": "12px",
        "margin-desktop": "48px",
        "base": "4px"
      },
      fontFamily: {
        "display-lg": ["Outfit", "sans-serif"],
        "title-card": ["Manrope", "sans-serif"],
        "body-main": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg-mobile": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "title-card": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-main": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
